### ISSUE TITLE
Audio track IDs not updated with values from the actual stream

### ISSUE THREAD

**Issue by mikepantazoglou** [Metrological/WebKitForWayland#1088]
The audio tracks of an `HTMLMediaElement` are currently being given dummy IDs by the `AudioTrackPrivateGStreamer` constructor in the form of A0, A1, A2, etc. Those IDs are not updated with the actual IDs from the stream as they should, e.g. using the following API:

`gst_pad_get_stream_id()`

By making use of the above API, the constructor has been modified with a temporary workaround as follows:

```
diff --git a/Source/WebCore/platform/graphics/gstreamer/AudioTrackPrivateGStreamer.cpp b/Source/WebCore/platform/graphics/gstreamer/AudioTrackPrivateGStreamer.cpp
index b74886405e94..ac3dd65b2532 100644
--- a/Source/WebCore/platform/graphics/gstreamer/AudioTrackPrivateGStreamer.cpp
+++ b/Source/WebCore/platform/graphics/gstreamer/AudioTrackPrivateGStreamer.cpp
@@ -38,8 +38,11 @@ AudioTrackPrivateGStreamer::AudioTrackPrivateGStreamer(WeakPtr<MediaPlayerPrivat
     : TrackPrivateBaseGStreamer(this, index, pad)
     , m_player(player)
 {
-    // FIXME: Get a real ID from the tkhd atom.
-    m_id = "A" + String::number(index);
+    gchar* idstr = gst_pad_get_stream_id(pad.get());
+    while (!idstr) {
+        idstr = gst_pad_get_stream_id(pad.get());
+    }
+    m_id = idstr;
 }
 
 AudioTrackPrivateGStreamer::AudioTrackPrivateGStreamer(WeakPtr<MediaPlayerPrivateGStreamer> player, gint index, GRefPtr<GstStream> stream)
```

By doing that, the execution blocks until an actual ID is received by the stream. Is there a proper way to get this information asynchronously? Note that, this issue seems to have been tackled in wpe-2.38.

**Comment by modeveci** [comment]
Hi @eocanha, could you please look at this issue? It is a blocker for HBBTV certification.

**Comment by vivienne-w** [comment]
We're currently looking into this.

**Comment by modeveci** [comment]
The proposed patch has been verified and merged. We can close this ticket @vivienne-w. Thank you.

**Comment by alkis-gkouzias-obs** [comment]
The patch looks legit, however, we could not verify it with our code and test cases. The problem is, the AppendPipeline is not being called at runtime. Instead, a different execution path is followed as explained below.

By inspecting the code flow, we could see that the process of playing an mp4 starts from the MediaPlayerPrivateGStreamer::loadFull(const String& urlString, const String& pipelineName) method which is located in Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp. Inside MediaPlayerPrivateGStreamer::createGSTPlayBin() is called, where two gstreamer signals are attached:
```
    if (m_isLegacyPlaybin) {
        g_signal_connect_swapped(m_pipeline.get(), "video-changed", G_CALLBACK(videoChangedCallback), this);
        g_signal_connect_swapped(m_pipeline.get(), "audio-changed", G_CALLBACK(audioChangedCallback), this);
    }
```
These callbacks are responsible for the video and audio tracks creation in our case. By inspecting for example the audioChangedCallback:

```
void MediaPlayerPrivateGStreamer::audioChangedCallback(MediaPlayerPrivateGStreamer* player)
{
    player->m_notifier->notify(MainThreadNotification::AudioChanged, [player] {
        player->notifyPlayerOfAudio();
    });
}
```
we can see that MediaPlayerPrivateGStreamer::notifyPlayerOfAudio() is called. Inside, the follwing code seems to be responsible for the creation and addition of audio tracks:

```
#if ENABLE(VIDEO_TRACK)
    Vector<String> validAudioStreams;
    for (unsigned i = 0; i < numTracks; ++i) {
        GRefPtr<GstPad> pad;
        g_signal_emit_by_name(m_pipeline.get(), "get-audio-pad", i, &pad.outPtr(), nullptr);
        ASSERT(pad);

        String streamId = "A" + String::number(i);
        validAudioStreams.append(streamId);
        if (i < m_audioTracks.size()) {
            RefPtr<AudioTrackPrivateGStreamer> existingTrack = m_audioTracks.get(streamId);
            if (existingTrack) {
                existingTrack->setIndex(i);
                if (existingTrack->pad() == pad)
                    continue;
            }
        }

        auto track = AudioTrackPrivateGStreamer::create(makeWeakPtr(*this), i, pad);
        if (!track->trackIndex())
            track->setActive(true);
        ASSERT(streamId == track->id());
        m_audioTracks.add(streamId, track);
        m_player->addAudioTrack(*track);
    }

    purgeInvalidAudioTracks(validAudioStreams);
#endif

    m_player->mediaEngineUpdated();
```    
    
This results into the constructor being called without passing a streamId and therefore the id values continue being dummy values. Is there any way we could add the equivalent changes in MediaPlayerPrivateGStreamer?

**Comment by mikepantazoglou** [comment]
@modeveci @vivienne-w 

Given the feedback provided by @alkis-gkouzias-obs above, could this issue be re-opened please?

**Comment by modeveci** [comment]
Re-opening based on feedback, @vivienne-w can you continue your investigation? Thank you!

**Comment by vivienne-w** [comment]
I changed `MediaPlayerPrivateGStreamer::notifyPlayerOfAudio()` to call the constructor with an explicit stream ID, just like the previous patch did for `AppendPipeline::connectDemuxerSrcPadToAppsink()`. Let me know if this works for you!

**Comment by alkis-gkouzias-obs** [comment]
Hello @vivienne-w. I have applied the changes but I now get a crash when running the test. It seems that the gst_pad_get_stream_id(pad.get()) returns NULL at this point. I have modified the code just to make sure:

```
        String streamId;
        if (gst_pad_get_stream_id(pad.get())) {
            StringView streamIdView(gst_pad_get_stream_id(pad.get()));
            size_t index = streamIdView.find('/');

            
            if (index == notFound)
                streamId = "A" + String::number(i);
            else
                streamId = streamId.substring(index + 1);
        } else {
            streamId = "A" + String::number(i);
        }
```
and with these changes, the browser will not crash, however the ids will be dummy values. Is there a way to get to the point of gst_pad_get_stream_id when the actual id is set?

**Comment by vivienne-w** [comment]
@alkis-gkouzias-obs I pushed some changes to the PR (#1109), can you try it again?

**Comment by alkis-gkouzias-obs** [comment]
Hello @vivienne-w 
Thank you for providing these changes. I was able to see the ids getting updated by this callback, however I could not get the changes in the javascript side. I have made some changes to the code:

```
struct StreamStartProbeData {
    MediaPlayerPrivateGStreamer* player_private;
    int trackIndex;
    MediaPlayer* media_player;
};


GstPadProbeReturn MediaPlayerPrivateGStreamer::streamStartProbeCallback(GstPad*, GstPadProbeInfo* info, gpointer data)
{
    auto probeData = (StreamStartProbeData*) data;
    auto audioTracks = probeData->player_private->m_audioTracks;

    if (info->type & GST_PAD_PROBE_TYPE_EVENT_BOTH) {
        GstEvent* event = GST_PAD_PROBE_INFO_EVENT (info);

        if (GST_EVENT_TYPE(event) == GST_EVENT_STREAM_START) {
            String streamId = audioTrackIdFromStreamStart(event);

            bool ok = false;
            for (auto& track : audioTracks.values()) {
                if (track->trackIndex() == probeData->trackIndex) {
                    probeData->media_player->removeAudioTrack(*track);
                    GST_DEBUG_OBJECT(probeData->player_private->pipeline(),
                        "Updated stream ID, old: %s, new: %s",
                        track->id().string().utf8().data(), streamId.utf8().data());
                    track->setId(streamId);
                    probeData->media_player->addAudioTrack(*track);
                    probeData->media_player->mediaEngineUpdated();
                    ok = true;
                    break;
                }
            }

            if (!ok)
                GST_WARNING_OBJECT(probeData->player_private->pipeline(),
                    "Failed to find audio track %d, cannot update stream ID",
                    probeData->trackIndex);

            return GST_PAD_PROBE_REMOVE;
        }
    }

    return GST_PAD_PROBE_OK;
}
```
I did add the m_player member variable in the handler custom data:

```
new StreamStartProbeData { this, static_cast<int>(i), m_player },
```
With these changes, I can see correct ids getting in the javascript side. However, I still get some tracks with dummy ids. Could we move the creation of the audio tracks inside this handler?

**Comment by vivienne-w** [comment]
@alkis-gkouzias-obs moving track creation into the probe sadly doesn't work out, for example it might spawn another probe for a pad that already has one. However I adopted your approach for the probe, and fixed track creation so that shouldn't be necessary anymore. Can you try one more time with the new changes?

**Comment by alkis-gkouzias-obs** [comment]
Hello @vivienne-w 

I have noticed the following issues after trying these changes.

1) the browser will occasionally crash - approx 2/10 test runs

2) when the browser does not crash, there is a chance that the ids will not be retrieved correctly. For example we can retrieve 3 audio tracks where the first id is A0 and the rest are correct, or the first two are A0, A1 and the third is correct. This seems random.

After looking more into the issue, I have found out that we can use the bus messages to listen for the STREAM_START event. When this message arrives, the sticky event is set on both video and audio pads and therefore gst_pad_get_sticky_event can be used to retrieve the ids. I have removed the signal connect for audio and video change:

    -if (m_isLegacyPlaybin) {
    -    g_signal_connect_swapped(m_pipeline.get(), "video-changed", G_CALLBACK(videoChangedCallback), this);
    -    g_signal_connect_swapped(m_pipeline.get(), "audio-changed", G_CALLBACK(audioChangedCallback), this);
    -}
    
and moved this logic to the STREAM_START handling instead:

    +case GST_MESSAGE_STREAM_START:
    +    unsigned numVidTracks;
    +    unsigned numAudTracks;

    +    g_object_get(m_pipeline.get(), "n-video", &numVidTracks, nullptr);
    +    g_object_get(m_pipeline.get(), "n-audio", &numAudTracks, nullptr);

    +    if (numVidTracks > 0)
    +        notifyPlayerOfVideo();
    +    if (numAudTracks > 0)
    +        notifyPlayerOfAudio();
    +    break;
    
I have extended the fix to the video tracks as well, since the same issue has been noticed for the video tracks. I am attaching the patch for these fixes; can this be used instead?
[update-track-ids-fix.patch.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/12069706/update-track-ids-fix.patch.txt)

**Comment by eocanha** [comment]
I've kept working on this and have evolved the design in the following ways:

1. Move the track reconfiguration logic to the main thread using a MainThreadNotifier. Unfortunately, due to the limitations on how MainThreadNotifier works, only the first notification is delivered (the rest are ignored because MainThreadNotifier thinks that just notifying once is enough, but that's very bad). What I did was to just try to update all the tracks (on the main thread) when the first (and single) notification arrives, using the sticky stream-start event. However, it turns out that not all stream-start events are stored as sticky events at that point, likely because that storage happens after the probe is processed and there's some kind of race between that and the main thread processing, but we can't control that beyond the scope of the probe. We needed a better way to know when the sticky stream-start events are available.

2. Partially follow [alkis' suggestion](https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/1088#issuecomment-1638038127) and use the stream-start bus message for that. That message is emitted by the pipeline, and at that point all the sticky events are properly stored. I've checked that under normal circumstances, even with the player paused on start (no autoplay), the stream-start bus message is emitted. However, the log messages I added have also detected that at the end of playback of a regular video, the player is sort of "reloaded", tracks are detected again, and the temporary track ids (A1, A2, A3...) are used, but no stream-start message is produced.

So, @alkis-gkouzias-obs, I'm going clean up my patch to follow the approach of producing temporary ids and then updating them on stream-start message. Let me know if that doesn't work for you.

**Comment by eocanha** [comment]
The new approach is on https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/1138. @alkis-gkouzias-obs, give it a try when you can and tell me if it works for you. Thanks!

**Comment by alkis-gkouzias-obs** [comment]
Hello @eocanha. Thank you for providing these changes. The changes indeed work well; I ran the test and I confirm that I am getting the audio ids successfully and consistently in the javascript side.

Just to clarify - The same problem is happening with the video track ids and the solution seems to be similar (getting the id from the bus stream start event). Can we extend this solution for the video tracks? If so, should it be done on a new GitHub issue?

**Comment by eocanha** [comment]
@alkis-gkouzias-obs: Done (updated https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/1138). I still would like to try to upstream this if possible, though.

**Comment by alkis-gkouzias-obs** [comment]
Thanks @eocanha . The tests concerning these changes are ok from my side.

**Comment by eocanha** [comment]
The issue has been reported upstream as https://bugs.webkit.org/show_bug.cgi?id=260520 and landed as https://github.com/WebKit/WebKit/commit/b750030983005416b9601a3ab58b3b3886dbbd90. It's been backported to wpe-2.38 as https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/dc705bc9c42536755a5cce3f218a6729a5da96d4 and to wpe-2.28 as https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/a2b9cb39fa82970515655f88d1221a552cc165f8.

**Comment by eocanha** [comment]
The fix has been backported to all the relevant branches. Closing issue.
